-- Create admin table
create table public.admin (
  id bigint generated by default as identity not null,
  username text not null,
  email text not null,
  password text not null,
  constraint admin_pkey primary key (id)
) TABLESPACE pg_default;

-- Add initial admin user
INSERT INTO public.admin (username, email, password)
VALUES ('Admin', 'sagayac697@elobits.com', 'admin123');