-- Add artikel_status column to artikel table
ALTER TABLE public.artikel
ADD COLUMN artikel_status text NOT NULL DEFAULT 'pending';

-- Create admin_comment table for article review comments
CREATE TABLE public.admin_comment (
  id bigint generated by default as identity not null,
  artikel_id bigint not null,
  admin_id bigint not null,
  comment text not null,
  created_at timestamp with time zone default now(),
  constraint admin_comment_pkey primary key (id),
  constraint admin_comment_artikel_id_fkey foreign key (artikel_id) references public.artikel(idartikel) on delete cascade,
  constraint admin_comment_admin_id_fkey foreign key (admin_id) references public.admin(id) on delete cascade
) TABLESPACE pg_default;

-- Add comment to artikel_status column
COMMENT ON COLUMN public.artikel.artikel_status IS 'Status artikel: pending, reviewed, approved, rejected, published';